line 1:15 token recognition error at: ';\r'
line 4:7 token recognition error at: '='
line 4:16 token recognition error at: ';\r'
line 5:11 token recognition error at: '='
line 5:14 token recognition error at: ';\r'
line 8:4 token recognition error at: 'a,'
line 8:7 token recognition error at: 'b,'
line 8:10 token recognition error at: 'c:'
line 8:20 token recognition error at: ';\r'
line 9:4 token recognition error at: 'r,'
line 9:11 token recognition error at: ':'
line 9:17 token recognition error at: ';\r'
line 11:20 token recognition error at: '(x:'
line 11:31 token recognition error at: '; '
line 11:33 token recognition error at: 'y:'
line 11:43 token recognition error at: ')'
line 11:44 token recognition error at: ';\r'
line 13:4 token recognition error at: 'd,'
line 13:7 token recognition error at: 'e,'
line 13:10 token recognition error at: 'f,'
line 13:13 token recognition error at: 'g:'
line 13:23 token recognition error at: ';\r'
line 14:6 token recognition error at: ','
line 14:10 token recognition error at: ','
line 14:14 token recognition error at: ','
line 14:19 token recognition error at: ':'
line 14:25 token recognition error at: ';\r'
line 16:11 token recognition error at: '('First '
line 16:24 token recognition error at: ':'
line 16:26 token recognition error at: '', '
line 16:29 token recognition error at: 'x)'
line 16:31 token recognition error at: ';\r'
line 17:11 token recognition error at: '('Second '
line 17:25 token recognition error at: ':'
line 17:27 token recognition error at: '', '
line 17:30 token recognition error at: 'y)'
line 17:32 token recognition error at: ';\r'
line 18:3 token recognition error at: ';\r'
line 20:17 token recognition error at: '(n1: '
line 20:29 token recognition error at: '; '
line 20:33 token recognition error at: ':'
line 20:42 token recognition error at: ')'
line 20:43 token recognition error at: ':'
line 20:52 token recognition error at: ';\r'
line 22:6 token recognition error at: ':'
line 22:15 token recognition error at: ';\r'
line 24:13 token recognition error at: ':'
line 24:14 token recognition error at: '='
line 24:23 token recognition error at: ';\r'
line 25:3 token recognition error at: ';\r'
line 27:19 token recognition error at: '(radius: '
line 27:32 token recognition error at: ')'
line 27:33 token recognition error at: ':'
line 27:39 token recognition error at: ';\r'
line 29:15 token recognition error at: ':'
line 29:16 token recognition error at: '='
line 29:38 token recognition error at: ';\r'
line 30:3 token recognition error at: ';\r'
line 33:4 token recognition error at: 'a '
line 33:6 token recognition error at: ':'
line 33:7 token recognition error at: '='
line 33:10 token recognition error at: ';\r'
line 34:4 token recognition error at: 'b '
line 34:6 token recognition error at: ':'
line 34:7 token recognition error at: '='
line 34:11 token recognition error at: ';\r'
line 35:4 token recognition error at: 'c '
line 35:6 token recognition error at: ':'
line 35:7 token recognition error at: '='
line 35:17 token recognition error at: '(a,'
line 35:21 token recognition error at: 'b)'
line 35:23 token recognition error at: ';\r'
line 37:14 token recognition error at: '(a,'
line 37:18 token recognition error at: 'c)'
line 37:20 token recognition error at: ';\r'
line 39:4 token recognition error at: 'r '
line 39:6 token recognition error at: ':'
line 39:7 token recognition error at: '='
line 39:12 token recognition error at: ';\r'
line 40:9 token recognition error at: ':'
line 40:10 token recognition error at: '='
line 40:22 token recognition error at: '(r)'
line 40:25 token recognition error at: ';\r'
line 42:11 token recognition error at: '('Radius:'
line 42:21 token recognition error at: '', '
line 42:24 token recognition error at: 'r)'
line 42:26 token recognition error at: ';\r'
line 43:11 token recognition error at: '('Area '
line 43:27 token recognition error at: ':'
line 43:29 token recognition error at: '', '
line 43:36 token recognition error at: ')'
line 43:37 token recognition error at: ';\r'
line 44:11 token recognition error at: '('Constant '
line 44:28 token recognition error at: ':'
line 44:30 token recognition error at: '', '
line 44:39 token recognition error at: ')'
line 44:40 token recognition error at: ';\r'
line 45:3 token recognition error at: '.'
